### PR TITLE
Enhancement: Switch from Travis CI to GitHub Actions

### LINKED ISSUE #19: Move CI to github actions

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] switches from Travis CI to GitHub Actions

Fixes #19.

💁‍♂️ You can see this in action in https://github.com/localheinz/engine/pull/1 (currently failing).

### CODE REVIEW

**Comment by theseer** [comment]
Thanks a lot already!

So on github actions it fails for the seemingly same reason it fails on travis ci.
Strange enough, I can neither reproduce this on my systems nor do I find anything useful on the shown error messages. There is *one* issue reported in xmlseclib that apparently has the same kind of issue. 

I'm confused :-/

**Comment by localheinz** [comment]
@theseer 

You are welcome!

I'm unsure how to fix the issue, though.

**Comment by theseer** [comment]
The issue is not the CI's fault.

It certainly is something I'm doing wrong in my code as it's an exception from libxml2 / DOM.

The problem is: I don't understand it, cannot find anything about it when googling and, worst, cannot reproduce it on my system.

**Comment by localheinz** [comment]
@theseer 

Fails on my system as well, but that probably does not help you.

**Comment by localheinz** [comment]
Thank you, @theseer!

**Pull request merged**
